BloodBankMS/BloodBankMS/urls.py
from django.contrib import admin
from django.urls import path, include
from bloodbank import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('donor/', views.donoruser, name='donoruser'),
    path('donordetails/<int:donor_id>/', views.donordetails, name='donordetails'),
    path('post/', include('bbpost.urls')),
    path('bank/', include('bank.urls')),
    path('donorreg/', views.donorreg, name='donorreg'),
    path('profile/', views.mdprofile, name='mdprofile'),
    path('edit/<int:d_pk>', views.dedit, name='dedit'),
    
]

BloodBankMS/bank/urls.py
from django.urls import path
from bank import views

app_name = 'bank'

urlpatterns = [
path('', views.bloodbank, name='bloodbank'),
]

BloodBankMS/bloodbank/models.py
from django.db import models
from django.contrib.auth.models import User

class BloodClass(models.Model):
    name = models.CharField(max_length=100)
    blood_group = models.CharField(max_length=3)
    age = models.IntegerField()
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=14)

    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

BloodBankMS/bloodbank/forms.py
from django.forms import ModelForm
from .models import BloodClass

class BloodForm(ModelForm):
    class Meta:
        model = BloodClass
        fields = ('name', 'age', 'blood_group','address','phone_number')

#All models name:
    # name = models.CharField(max_length=100)
    # blood_group = models.CharField(max_length=3)
    # age = models.IntegerField()
    # address = models.CharField(max_length=250)
    # phone_number = models.CharField(max_length=14)

    # user = models.ForeignKey(User,on_delete=models.CASCADE)

BloodBankMS/bloodbank/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import BloodClass
from .forms import BloodForm


def home(request):
    return render(request, 'bloodbank/home.html')


def signupuser(request):
    if request.method=='GET':
        return render(request, 'bloodbank/signupuser.html',{'form':UserCreationForm})
    else:
        if request.POST['password1']==request.POST['password2']:
            try:
                user=User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'bloodbank/signupuser.html', {'form':UserCreationForm,'error':'username has been already taken'})
        else:
            return render(request, 'bloodbank/signupuser.html', {'form':UserCreationForm,'error':'password did not match'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'bloodbank/login.html', {'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'bloodbank/login.html', {'form':AuthenticationForm(), 'error':'Error! Try again with correct username & password'})
        else:
            login(request, user)
            return redirect('home')

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

@login_required
def donoruser(request):
    form = BloodClass.objects.all()
    return render(request,'bloodbank/donor.html', {'form':form})

@login_required
def donordetails(request,donor_id):
    dd = get_object_or_404(BloodClass, pk=donor_id)
    return render(request,'bloodbank/donordetails.html', {'dd':dd})

@login_required
def donorreg(request):
    if request.method == 'GET':
        return render(request, 'bloodbank/donorreg.html', {'form':BloodForm()})
    else:
        try:
            dr = BloodForm(request.POST)
            new_dr = dr.save(commit=False)
            new_dr.user = request.user
            new_dr.save()
            return redirect('donoruser')

        except ValueError:
            return render(request, 'bloodbank/donorreg.html', {'form':BloodForm(), 'error':'Error! Try again!'})

@login_required
def mdprofile(request):
    form = BloodClass.objects.filter(user= request.user)
    return render(request,'bloodbank/myprofile.html', {'form':form})

@login_required
def dedit(request, d_pk):
    obj = get_object_or_404(BloodClass, pk=d_pk,user=request.user)
    if request.method=='GET':
        dform=BloodForm(instance=obj)
        return render(request,'bloodbank/edit.html',{'dform':dform,'obj':obj})
    else:
        try:
            dform = BloodForm(request.POST,instance=obj)
            dform.save()
            return redirect('mdprofile')
        except ValueError:
            return render(request,'bloodbank/edit.html',{'dform':dform,'obj':obj,'error':'Error! Try again'} )

BloodBankMS/bloodbank/templates/bloodbank/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bloodbank/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bloodbank/testcss.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png"  href="{% static 'bloodbank/LogoMakr-1AIuCn.png' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    

    <script>
      function count(){
        document.querySelector('.var2').innerHTML="People live when people give.";
        document.querySelector('.var1').innerHTML="You don't have to be doctor to save lives";
      }
      function count1(){
        document.querySelector('.var10').innerHTML="About Us";
        document.querySelector('.var11').innerHTML="<br>Name - FARHANA ISLAM URMI <br>Github - Github.com/Farhanaurmi<br><br>Name - MAHADI HASAN TANMOY <br>Github - Github.com/mhtanmoy<br><br>";
      }
      function count2(){
        document.querySelector('.var10').innerHTML="Contact";
        document.querySelector('.var11').innerHTML="<br>E-mail: farhanaurmi760@gmail.com<br>E-mail: Mahadi.std@gmail.com<br><br>";
      }
    </script>
    <title>Blood-Bank</title>
</head>

<body>
    <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
        <div class="container-fluid">
        <div class="navbar-header">
            <a href="{% url 'home' %}" class="navbar-brand btn btn-dark">
            <img src="{% static 'bloodbank/LogoMakr-1AIuCn.png' %}" width="30" height="30" class="d-inline-block align-top">
            <span>Blood Bank</span>
            </a>
        </div>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item"><button type="button"  class="btn btn-dark">|| Logged In as {{ user.username }} ||</button></li>
            <li class="nav-item">
                <form method="POST" action="{% url 'logoutuser' %}">
                    {% csrf_token %}
                <button type="submit"  class="btn btn-dark">Log-Out</button>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item"> 
                <a class="btn btn-dark" href="{% url 'signupuser' %}">Sign Up </a> 
            </li>
            <li class="nav-item">
                <a class="btn btn-dark" href="{% url 'loginuser' %}">Login</a>
            </li>
        </ul>
        {% endif %}
    </div>
    </nav>
    <div class="container-fluid">
        <br>
        <br>
        <br>
        <br>
    {% block content %}{% endblock %}
</div>
</body>
</html>

BloodBankMS/bloodbank/templates/bloodbank/bloodbank.html
{% extends 'bloodbank/base.html' %}
{% block content %}
<br><br><br><br>
{% for i in bbform %}
<div class="jumbotron">
<h3>{{ i.name }}</h3>
<h3>{{ i.phone_number }}</h3>
<h3>{{ i.address }}</h3>
</div>
{% endfor %}


{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/bloodbank_info.html
<h1>Blood Bank Info</h1>

BloodBankMS/bloodbank/templates/bloodbank/donor.html
{% extends 'bloodbank/base.html' %}
{% block content %}
<br><br><br><br>
{% for i in form %}

<div class="jumbotron">
<a href="{% url 'donordetails' i.id %}"><h3>{{ i.name }}-{{ i.blood_group }}</h3></a>
</div>

{% endfor %}
{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/donordetails.html
{% extends 'bloodbank/base.html' %}
{% block content %}
<br><br><br><br>
<div class="jumbotron">
<h3>|Name| {{ dd.name }}</h3>
<h3>|Age | {{ dd.age }}</h3>
<h3>|Blood Group| {{ dd.blood_group }}</h3>
<h3>|Phone| {{ dd.phone_number }}</h3>
<h3>|Address| {{ dd.address }}</h3>
</div>

{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/donorreg.html
{% load static %}
<link rel="stylesheet" href="{% static 'bloodbank/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bloodbank/testcss.css' %}">

<dir class="jumbotron text-center">

<h2>{{ error }}</h2>

<form method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
<button type="submit" class="btn btn-secondary">Create</button> &nbsp; &nbsp;
<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
</form>
</dir>

BloodBankMS/bloodbank/templates/bloodbank/edit.html
<br>
<br>
<br>
<br>

{% load static %}
<link rel="stylesheet" href="{% static 'bloodbank/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bloodbank/testcss.css' %}">

<dir class="jumbotron text-center">
    <h2>{{ error }}</h2>

    {{ obj.name }}
    <form method="POST" >
        {% csrf_token %}
    {{ dform.as_p }}
    
    <button type="submit" class="btn btn-secondary">Save</button>&nbsp; &nbsp;
    <a href="{% url 'mdprofile' %}" class="btn btn-secondary">Back</a>

    </form>

</dir>

BloodBankMS/bloodbank/templates/bloodbank/home.html
{% extends 'bloodbank/base.html' %}
{% block content %}

<div class="var0 jumbotron">
    <div id="bgd">
        <h1 class="display-3"><span class="var2">People live when people give.</span></h1>
        <p class="var1 lead">Every blood donor is a life saver</p>
        <p class="lead">
            <a class="var3" onclick="count()" role="button"><span>More..</span></a>
        </p>
    </div>
    </div>


<br><br><br><br>
<div class="jumbotron text-center">
    <div class="btn-group btn-group-vertical ">
    <a href="{% url 'bank:bloodbank' %}" class="btn btn-dark"> Bloodbank</a>
    <br>
    <br>
    <a href="{% url 'donoruser' %}" class="btn btn-dark" >Donor List</a>
    <br>
    <br>
    <a href="{% url 'bbpost_home' %}" class="btn btn-dark" >All Post</a>
    <br>
    <br>
    <a href="{% url 'donorreg' %}" class="btn btn-dark">Donor Register</a>
    <br>
    <br>
    <a href="{% url 'mdprofile' %}" class="btn btn-dark">Donor profile</a>
<br>
<br>
</div>

{% load static %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="pic d-block w-100" src="{% static 'bloodbank/1.png' %}" alt="First slide" height="auto" width="auto">
      </div>
      <div class="carousel-item">
        <img class="pic d-block w-100" src="{% static 'bloodbank/2.png' %}" alt="Second slide" height="auto" width="auto">
      </div>
      <div class="carousel-item">
        <img class="pic d-block w-100" src="{% static 'bloodbank/3.png' %}" alt="Third slide" height="auto" width="auto">
      </div>
    </div>
  </div>


<div class="var0 jumbotron">
    <div id="bgd">
        <h1 class="display-3"><span class="var10"></span></h1>
        <p class="var11 lead"></p>
        <p class="lead">
            <a class="var12" onclick="count1()" role="button"><span class="btn btn-dark">About Us </span></a>
            <a class="var12" onclick="count2()" role="button"><span class="btn btn-dark">Contact Us </span></a>
        </p>
    </div>
    </div>
    
{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/login.html
{% extends 'bloodbank/base.html' %}
{% block content %}
<br><br><br><br>
<div class="jumbotron">
<h1>Sign-in Form</h1>
<h2>{{ error }}</h2>

<form method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
<button type="submit" class="btn btn-secondary">Sign-In</button>
</form>
</div>
{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/myprofile.html
{% extends 'bloodbank/base.html' %}
{% block content %}
<br><br><br><br>
{% for i in form %}
<div class="jumbotron">
<a href="{% url 'dedit' i.id %}"><h3>Name: {{ i.name }} ({{ i.blood_group }})</h3></a>
</div>
{% endfor %}
{% endblock %}

BloodBankMS/bloodbank/templates/bloodbank/signupuser.html
{% extends 'bloodbank/base.html' %}
{% block content %}

<h3 class="btn btn-secondary">{{ error }}</h3>
<div class="jumbotron">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

<button type="submit" class="btn btn-secondary">Sign Up</button>
</div>
</form>

{% endblock %}